### ISSUE TITLE
gradlew failed，how to fix

### ISSUE THREAD

**Issue by xdthesun** [TarCV/uiautomatorviewer-gradle#45]
$ ./gradlew installDist

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'uiautomatorviewer-gradle'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve dev.equo.ide:equo-ide-gradle-plugin:1.7.6.
     Required by:
         project : > dev.equo.p2deps:dev.equo.p2deps.gradle.plugin:1.7.6
      > No matching variant of dev.equo.ide:equo-ide-gradle-plugin:1.7.6 was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.5' but:
          - Variant 'apiElements' capability dev.equo.ide:equo-ide-gradle-plugin:1.7.6 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 11 and the consumer needed a component for use during runtime, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.5')
          - Variant 'javadocElements' capability dev.equo.ide:equo-ide-gradle-plugin:1.7.6 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.5')
          - Variant 'runtimeElements' capability dev.equo.ide:equo-ide-gradle-plugin:1.7.6 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 11 and the consumer needed a component, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.5')
          - Variant 'sourcesElements' capability dev.equo.ide:equo-ide-gradle-plugin:1.7.6 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.5')

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 831ms

**Comment by TarCV** [comment]
`- Incompatible because this component declares a component for use during compile-time, compatible with Java 11 and the consumer needed a component for use during runtime, compatible with Java 8`
From the message it looks like you have JDK 8, but UI components require JDK 11+. Could you try running the command with Java 11 (or later)?

**Comment by TarCV** [comment]
Hopefully, the above comment helped you. Closing the issue for now.
